# CMake toolchain — FreeBSD x86_64 (Clang cross-compile)
set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

# Sysroot: /opt/sysroots/freebsd-x86_64 (local) or /tmp/freebsd-sysroot (CI)
if(EXISTS /opt/sysroots/freebsd-x86_64/usr/include)
    set(FREEBSD_SYSROOT /opt/sysroots/freebsd-x86_64)
elseif(EXISTS /tmp/freebsd-sysroot/usr/include)
    set(FREEBSD_SYSROOT /tmp/freebsd-sysroot)
else()
    message(FATAL_ERROR "FreeBSD x86_64 sysroot not found. Install at /opt/sysroots/freebsd-x86_64 or /tmp/freebsd-sysroot")
endif()

set(CMAKE_C_FLAGS "--target=x86_64-unknown-freebsd14 --sysroot=${FREEBSD_SYSROOT}")
set(CMAKE_CXX_FLAGS "--target=x86_64-unknown-freebsd14 --sysroot=${FREEBSD_SYSROOT}")
set(CMAKE_ASM_FLAGS "--target=x86_64-unknown-freebsd14 --sysroot=${FREEBSD_SYSROOT}")
set(CMAKE_EXE_LINKER_FLAGS "--target=x86_64-unknown-freebsd14 --sysroot=${FREEBSD_SYSROOT} -fuse-ld=lld")

set(CMAKE_FIND_ROOT_PATH "${FREEBSD_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
