name = "manual_pointer_borrow"
defaultTargets = ["ManualPointerBorrow", "ManualPointerBorrowConstraints"]

[[lean_lib]]
name = "ManualPointerBorrow"
srcDir = "src"

[[lean_lib]]
name = "ManualPointerBorrowConstraints"
srcDir = "src"
roots = ["ManualPointerBorrowConstraints"]
