// runtime_smf_socket_shims.c — host-runtime (SMF loader) TCP socket symbols.
//
// The SMF loader resolves runtime relocations against symbols linked into the
// `simple-runtime` host crate (see RUNTIME_SYMBOL_ENTRIES, generated by
// runtime/build.rs from RUNTIME_SYMBOL_NAMES intersected with DEFINED symbols).
//
// The std.nogc_sync_mut.http_server package transitively references a class of
// rt_io_tcp_* socket externs. Most are Rust-defined in runtime/src/value/net_tcp.rs,
// but these six have NO host-linkable definition — they exist only in
// runtime_native.c, which is compiled into the AOT/native-project lane (an
// independent ABI universe) and is NOT linked into the host runtime. Any SMF that
// links the http_server path therefore fails at load: "Undefined symbol:
// rt_io_tcp_socket_create".
//
// This file provides exactly those six as host-linkable C symbols so the loader's
// static symbol registry can resolve them when this source is explicitly linked.
// The host RuntimeValue functions, including rt_io_tcp_bind_fd, are owned by the
// Rust runtime (`value/net_tcp.rs`) and MUST NOT be shadowed by failure stubs.

#include <stdint.h>
#include <stdbool.h>

#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  include <winsock2.h>
#  include <ws2tcpip.h>
#  pragma comment(lib, "Ws2_32.lib")

static void _ws_init(void) {
    static int done = 0;
    if (!done) { WSADATA wd; WSAStartup(MAKEWORD(2,2), &wd); done = 1; }
}

int64_t rt_io_tcp_socket_create(int64_t family) {
    _ws_init();
    if (family != 0 && family != 1) return -1;
    int af = family == 1 ? AF_INET6 : AF_INET;
    SOCKET s = socket(af, SOCK_STREAM, IPPROTO_TCP);
    return (s == INVALID_SOCKET) ? -1 : (int64_t)s;
}

bool rt_io_tcp_listen(int64_t fd, int64_t backlog) {
    return listen((SOCKET)fd, (int)backlog) == 0;
}

bool rt_io_tcp_set_nonblocking(int64_t fd, bool enabled) {
    u_long mode = enabled ? 1 : 0;
    return ioctlsocket((SOCKET)fd, FIONBIO, &mode) == 0 ? 1 : 0;
}

bool rt_io_tcp_set_reuseaddr(int64_t fd, bool enabled) {
    int flag = enabled ? 1 : 0;
    return setsockopt((SOCKET)fd, SOL_SOCKET, SO_REUSEADDR, (const char*)&flag, sizeof(flag)) == 0 ? 1 : 0;
}

bool rt_io_tcp_set_reuseport(int64_t fd, bool enabled) {
    /* SO_REUSEPORT is not available on Windows; return 0 (not supported). */
    (void)fd; (void)enabled; return 0;
}

#else /* POSIX */

#include <fcntl.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>

int64_t rt_io_tcp_socket_create(int64_t family) {
    if (family != 0 && family != 1) return -1;
    int af = family == 1 ? AF_INET6 : AF_INET;
    return (int64_t)socket(af, SOCK_STREAM, 0);
}

bool rt_io_tcp_listen(int64_t fd, int64_t backlog) {
    return listen((int)fd, (int)backlog) == 0;
}

bool rt_io_tcp_set_nonblocking(int64_t fd, bool enabled) {
    int flags = fcntl((int)fd, F_GETFL, 0);
    if (flags < 0) return 0;
    if (enabled) flags |= O_NONBLOCK; else flags &= ~O_NONBLOCK;
    return fcntl((int)fd, F_SETFL, flags) == 0 ? 1 : 0;
}

bool rt_io_tcp_set_reuseaddr(int64_t fd, bool enabled) {
    int flag = enabled ? 1 : 0;
    return setsockopt((int)fd, SOL_SOCKET, SO_REUSEADDR, &flag, sizeof(flag)) == 0 ? 1 : 0;
}

bool rt_io_tcp_set_reuseport(int64_t fd, bool enabled) {
#ifdef SO_REUSEPORT
    int flag = enabled ? 1 : 0;
    return setsockopt((int)fd, SOL_SOCKET, SO_REUSEPORT, &flag, sizeof(flag)) == 0 ? 1 : 0;
#else
    (void)fd; (void)enabled; return 0;
#endif
}

#endif /* _WIN32 */
