#!/bin/bash
# ECMAScript Compatibility Test Suite
# Tests against the official spec categories from Test262
# Run: bash test/js/compat_test.sh

BIN="bin/simple src/app/js/main.spl -e"
PASS=0
FAIL=0
TOTAL=0
FAILURES=""

check() {
    local desc="$1"
    local code="$2"
    local expected="$3"
    TOTAL=$((TOTAL + 1))
    local actual
    actual=$(eval $BIN \"\$code\" 2>/dev/null)
    if [ "$actual" = "$expected" ]; then
        PASS=$((PASS + 1))
        echo "  PASS: $desc"
    else
        FAIL=$((FAIL + 1))
        echo "  FAIL: $desc"
        echo "    code:     $code"
        echo "    expected: $expected"
        echo "    got:      $actual"
        FAILURES="$FAILURES\n  FAIL: $desc\n    code: $code\n    expected: $expected\n    got: $actual"
    fi
}

echo "ECMAScript Compatibility Test Suite"
echo "===================================="
echo ""

# ── 7. Lexical Grammar ──
echo "7. Lexical Grammar"
check "string escape \\n" "'\n'.length" "1"
check "string escape \\t" "'\t'.length" "1"
check "unicode escape" $'\'\\u0041\'' "A"
check "hex literal" "0xFF" "255"
check "octal-style" "010" "10"
check "binary literal" "0b1010" "10"
check "numeric separator" "1_000" "1000"
check "template literal" '`hello ${"world"}`' "hello world"
check "tagged template" '`${1+2}`' "3"

# ── 8. Types ──
echo ""
echo "8. Types"
check "undefined type" "typeof undefined" "undefined"
check "null type" "typeof null" "object"
check "boolean type" "typeof true" "boolean"
check "number type" "typeof 42" "number"
check "string type" "typeof 'hi'" "string"
check "object type" "typeof {}" "object"
check "function type" "typeof function(){}" "function"
check "symbol type" "typeof Symbol()" "symbol"
check "NaN is number" "typeof NaN" "number"
check "Infinity is number" "typeof Infinity" "number"

# ── 8.1 Undefined ──
echo ""
echo "8.1 Undefined"
check "void 0" "void 0" "undefined"
check "undefined var" "var x; typeof x" "undefined"

# ── 8.2 Null ──
echo ""
echo "8.2 Null"
check "null equality" "null == undefined" "true"
check "null strict" "null === undefined" "false"
check "null type coerce" "null + 1" "1"

# ── 8.3 Boolean ──
echo ""
echo "8.3 Boolean"
check "true" "true" "true"
check "false" "false" "false"
check "Boolean(0)" "!!0" "false"
check "Boolean(1)" "!!1" "true"
check "Boolean('')" "!!''" "false"
check "Boolean('x')" "!!'x'" "true"
check "Boolean(null)" "!!null" "false"
check "Boolean(undefined)" "!!undefined" "false"

# ── 8.4 String ──
echo ""
echo "8.4 String"
check "string concat" "'a' + 'b'" "ab"
check "string length" "'hello'.length" "5"
check "charAt" "'abc'.charAt(1)" "b"
check "indexOf" "'hello'.indexOf('ll')" "2"
check "indexOf not found" "'hello'.indexOf('xyz')" "-1"
check "slice" "'hello'.slice(1,3)" "el"
check "toUpperCase" "'abc'.toUpperCase()" "ABC"
check "toLowerCase" "'ABC'.toLowerCase()" "abc"
check "trim" "'  hi  '.trim()" "hi"
check "split" "'a,b,c'.split(',').length" "3"
check "startsWith" "'hello'.startsWith('hel')" "true"
check "endsWith" "'hello'.endsWith('llo')" "true"
check "includes" "'hello'.includes('ell')" "true"
check "repeat" "'ab'.repeat(3)" "ababab"
check "replace" "'hello'.replace('l','r')" "herlo"
check "replaceAll" "'hello'.replaceAll('l','r')" "herro"
check "padStart" "'5'.padStart(3,'0')" "005"
check "at positive" "'hello'.at(1)" "e"
check "at negative" "'hello'.at(-1)" "o"
check "string subscript" "'abc'[1]" "b"
check "substring" "'hello'.substring(1,3)" "el"

# ── 8.5 Number ──
echo ""
echo "8.5 Number"
check "integer" "42" "42"
check "float" "3.14" "3.14"
check "negative" "-5" "-5"
check "NaN check" "isNaN(NaN)" "true"
check "isFinite" "isFinite(42)" "true"
check "parseInt" "parseInt('42')" "42"
check "parseFloat" "parseFloat('3.14')" "3.14"
check "parseInt hex" "parseInt('0xFF', 16)" "255"
check "Number.isInteger true" "Number.isInteger(5)" "true"
check "Number.isInteger false" "Number.isInteger(5.5)" "false"
check "Infinity" "Infinity > 999999" "true"
check "negative zero" "-0 === 0" "true"

# ── 11. Expressions ──
echo ""
echo "11. Expressions"
check "addition" "1 + 2" "3"
check "subtraction" "5 - 3" "2"
check "multiplication" "6 * 7" "42"
check "division" "15 / 3" "5"
check "modulo" "10 % 3" "1"
check "exponent" "2 ** 10" "1024"
check "unary minus" "-5" "-5"
check "unary plus" "+'3'" "3"
check "prefix increment" "var x=5; ++x" "6"
check "postfix increment" "var x=5; x++; x" "6"
check "prefix decrement" "var x=5; --x" "4"
check "postfix decrement" "var x=5; x--; x" "4"
check "logical AND" "true && false" "false"
check "logical OR" "false || true" "true"
check "logical NOT" "!false" "true"
check "nullish coalesce" "null ?? 42" "42"
check "ternary" "true ? 'yes' : 'no'" "yes"
check "comma operator" "(1, 2, 3)" "3"
check "typeof" "typeof 42" "number"
check "void" "void 0" "undefined"
check "delete" "var o={a:1}; delete o.a; 'a' in o" "false"
check "in operator" "var o={a:1}; 'a' in o" "true"
check "strict equality" "1 === 1" "true"
check "strict inequality" "1 !== '1'" "true"
check "abstract equality" "1 == '1'" "true"
check "abstract inequality" "1 != '2'" "true"
check "less than" "1 < 2" "true"
check "greater than" "2 > 1" "true"
check "less equal" "1 <= 1" "true"
check "greater equal" "2 >= 2" "true"
check "bitwise AND" "5 & 3" "1"
check "bitwise OR" "5 | 3" "7"
check "bitwise XOR" "5 ^ 3" "6"
check "bitwise NOT" "~5" "-6"
check "compound +=" "var x=10; x+=5; x" "15"
check "compound -=" "var x=10; x-=3; x" "7"
check "compound *=" "var x=2; x*=3; x" "6"

# ── 12. Statements ──
echo ""
echo "12. Statements"
check "var declaration" "var x=5; x" "5"
check "let declaration" "let x=42; x" "42"
check "const declaration" "const x=99; x" "99"
check "if-else true" "if(true) 'yes'; else 'no'" "yes"
check "if-else false" "if(false) 'yes'; else 'no'" "no"
check "while loop" "var i=0; while(i<3){i=i+1;} i" "3"
check "do-while" "var i=0; do{i=i+1;}while(i<3); i" "3"
check "for loop" "var s=0; for(var i=0;i<5;i++){s=s+i;} s" "10"
check "for-in" "var o={a:1,b:2}; var k=''; for(var x in o){k=k+x;} k" "ab"
check "for-of array" "var s=0; for(var x of [1,2,3]){s=s+x;} s" "6"
check "switch case" "var r; switch(2){case 1: r='one'; break; case 2: r='two'; break;} r" "two"
check "switch default" "var r; switch(9){case 1: r='one'; break; default: r='other';} r" "other"
check "break in loop" "var i=0; while(true){if(i>=3)break; i++;} i" "3"
check "continue" "var s=0; for(var i=0;i<5;i++){if(i%2===0)continue; s+=i;} s" "4"
check "try-catch" "try{throw 'err';}catch(e){e}" "err"
check "try-catch-finally" "var r=''; try{r+='t';}catch(e){r+='c';}finally{r+='f';} r" "tf"
check "throw" "try{throw 42;}catch(e){e}" "42"
check "labeled stmt" "outer: for(var i=0;i<3;i++){break;} i" "0"

# ── 13. Functions ──
echo ""
echo "13. Functions"
check "function decl" "function f(x){return x*2;} f(5)" "10"
check "function expr" "var f = function(x){return x+1;}; f(9)" "10"
check "arrow single" "var f = x => x+1; f(5)" "6"
check "arrow multi" "var f = (a,b) => a+b; f(2,3)" "5"
check "arrow block" "var f = x => { return x*2; }; f(5)" "10"
check "default params" "function f(x,y){if(y===undefined)y=10; return x+y;} f(1)" "11"
check "rest-like" "function f(){var s=0; for(var i=0;i<arguments.length;i++){s+=arguments[i];} return s;} f(1,2,3)" "6"
check "closure" "function outer(){var x=5; return function(){return x;};} outer()()" "5"
check "closure counter" "function make(){var n=0; return function(){n++;return n;};} var c=make(); c(); c(); c()" "3"
check "recursion" "function fib(n){if(n<=1)return n; return fib(n-1)+fib(n-2);} fib(10)" "55"
check "IIFE" "(function(){return 42;})()" "42"

# ── 14. Classes ──
echo ""
echo "14. Classes"
check "class constructor" "class Foo{constructor(x){this.x=x}} var f=new Foo(42); f.x" "42"
check "class method" "class C{constructor(v){this.v=v} get(){return this.v}} var c=new C(5); c.get()" "5"
check "class extends" "class A{constructor(n){this.n=n}} class B extends A{constructor(n){this.n=n} f(){return this.n}} var b=new B(7); b.f()" "7"
check "new operator" "function P(n){this.name=n} var p=new P('Alice'); p.name" "Alice"

# ── 15. Built-in Objects ──
echo ""
echo "15. Built-in Objects"
check "Math.floor" "Math.floor(3.7)" "3"
check "Math.ceil" "Math.ceil(3.2)" "4"
check "Math.round" "Math.round(3.5)" "4"
check "Math.abs" "Math.abs(-5)" "5"
check "Math.max" "Math.max(1,5,3)" "5"
check "Math.min" "Math.min(5,2,8)" "2"
check "Math.sqrt" "Math.sqrt(16)" "4"
check "Math.pow" "Math.pow(2,8)" "256"
check "Math.PI" "Math.PI > 3.14" "true"
check "JSON.stringify obj" "JSON.stringify({a:1})" '{"a":1}'
check "JSON.stringify arr" "JSON.stringify([1,2,3])" "[1,2,3]"
check "JSON.stringify str" 'JSON.stringify("hello")' '"hello"'
check "JSON.stringify null" "JSON.stringify(null)" "null"
check "JSON.stringify bool" "JSON.stringify(true)" "true"
check "console.log" "console.log('test'); 'ok'" "ok"
check "Object.keys" "Object.keys({a:1,b:2}).length" "2"
check "Object.values" "Object.values({a:1,b:2}).join(',')" "1,2"
check "Object.assign" "Object.assign({},{a:1,b:2}).a" "1"
check "Array.isArray true" "Array.isArray([1,2])" "true"
check "Array.isArray false" "Array.isArray(42)" "false"
check "Error constructor" "try{throw new Error('x');}catch(e){'caught'}" "caught"
check "TypeError on undef" "try{undefined.x;}catch(e){'caught'}" "caught"

# ── 22. Array methods ──
echo ""
echo "22. Array Methods"
check "push" "var a=[]; a.push(1); a.push(2); a.length" "2"
check "pop" "var a=[1,2,3]; a.pop()" "3"
check "shift" "var a=[1,2,3]; a.shift()" "1"
check "unshift" "var a=[1,2]; a.unshift(0); a.join(',')" "0,1,2"
check "indexOf" "[1,2,3].indexOf(2)" "1"
check "includes" "[1,2,3].includes(2)" "true"
check "join" "[1,2,3].join('-')" "1-2-3"
check "reverse" "var a=[1,2,3]; a.reverse(); a.join(',')" "3,2,1"
check "slice" "[1,2,3,4].slice(1,3).join(',')" "2,3"
check "concat" "[1,2].concat([3,4]).join(',')" "1,2,3,4"
check "splice" "var a=[1,2,3,4]; a.splice(1,2); a.join(',')" "1,4"
check "sort" "var a=[3,1,2]; a.sort((a,b)=>a-b); a.join(',')" "1,2,3"
check "map" "[1,2,3].map(x=>x*2).join(',')" "2,4,6"
check "filter" "[1,2,3,4].filter(x=>x>2).join(',')" "3,4"
check "reduce" "[1,2,3].reduce((a,b)=>a+b,0)" "6"
check "find" "[1,2,3].find(x=>x>1)" "2"
check "findIndex" "[1,2,3].findIndex(x=>x>1)" "1"
check "some true" "[1,2,3].some(x=>x>2)" "true"
check "some false" "[1,2,3].some(x=>x>5)" "false"
check "every true" "[1,2,3].every(x=>x>0)" "true"
check "every false" "[1,2,3].every(x=>x>1)" "false"
check "forEach" "var s=0; [1,2,3].forEach(x=>{s=s+x}); s" "6"
check "flat" "[1,[2,3],[4]].flat().join(',')" "1,2,3,4"
check "flatMap" "[1,2,3].flatMap(x=>[x,x*2]).join(',')" "1,2,2,4,3,6"
check "at positive" "[1,2,3].at(1)" "2"
check "at negative" "[1,2,3].at(-1)" "3"

# ── 23. Destructuring ──
echo ""
echo "23. Destructuring"
check "object destruct" "var {a,b} = {a:1,b:2}; a+b" "3"
check "array destruct" "var [x,y] = [10,20]; x+y" "30"
check "spread rest" "var [x,...rest] = [1,2,3]; rest.length" "2"
check "spread in array" "[...[1,2],...[3,4]].length" "4"

# ── Summary ──
echo ""
echo "===================================="
echo "Results: $PASS/$TOTAL passed, $FAIL failed"
if [ $FAIL -gt 0 ]; then
    echo ""
    echo "Failures summary:"
    echo -e "$FAILURES"
fi
