/-
  Generated_Types.lean - Auto-generated Lean type definitions

  Module: TypeInferenceCompile
  Generated by: verification.lean.auto_gen

  DO NOT EDIT: This file is auto-generated. Changes will be overwritten.
  Manual code belongs in Classes.lean and Traits.lean.
-/

-- ════════════════════════════════════════════════════════════════
-- Base Types (from Classes.lean)
-- ════════════════════════════════════════════════════════════════

-- Type variables for polymorphism
inductive TyVar where
  | mk (id : Nat)
  deriving DecidableEq, Repr

-- Types in the class system
inductive Ty where
  | int                            -- Int type
  | bool                           -- Bool type
  | str                            -- Str type
  | var (v : TyVar)               -- Type variable
  | named (name : String)          -- Named type (class name)
  | arrow (params : List Ty) (ret : Ty)  -- Function type
  | generic (name : String) (args : List Ty)  -- Generic type: Class[T, U]
  deriving BEq, Repr

-- ════════════════════════════════════════════════════════════════
-- Class Definitions (from Classes.lean)
-- ════════════════════════════════════════════════════════════════

-- Field definition in a class
structure FieldDef where
  name : String
  ty : Ty
  deriving Repr

-- Method definition in a class
structure MethodDef where
  name : String
  self_ty : Ty                     -- Type of self parameter
  params : List Ty                 -- Other parameter types
  ret : Ty                         -- Return type
  deriving Repr

-- Class definition
structure ClassDef where
  name : String
  type_params : List TyVar         -- Generic type parameters
  fields : List FieldDef           -- Class fields
  methods : List MethodDef         -- Class methods
  parent : Option String           -- Parent class name (for inheritance)
  deriving Repr

-- ════════════════════════════════════════════════════════════════
-- Trait Definitions (from Traits.lean)
-- ════════════════════════════════════════════════════════════════

-- Associated type binding
structure AssocType where
  name : String
  ty : Ty
  deriving Repr

-- Method signature in a trait
structure TraitMethod where
  name : String
  self_ty : Ty                     -- Type of self (can be a type variable)
  params : List Ty
  ret : Ty
  deriving Repr

-- Trait definition
structure TraitDef where
  name : String
  type_params : List TyVar         -- Generic type parameters on the trait
  methods : List TraitMethod       -- Required methods
  assoc_types : List String        -- Associated type names
  parent_traits : List String      -- Parent traits (for trait inheritance)
  deriving Repr

-- Trait implementation
structure TraitImpl where
  trait_name : String              -- Trait being implemented
  for_type : Ty                    -- Type implementing the trait
  type_params : List TyVar         -- Type parameters (for generic impls)
  assoc_type_bindings : List AssocType  -- Associated type bindings
  method_impls : List (String × Ty)     -- Method name -> implementation type
  where_clause : List (Ty × String)     -- Type bounds: (Type, TraitName) pairs
  deriving Repr

-- ════════════════════════════════════════════════════════════════
-- Static Polymorphism (from Traits.lean)
-- ════════════════════════════════════════════════════════════════

-- Interface binding: binds a trait to an implementation type for static dispatch
structure InterfaceBinding where
  trait_name : String        -- The trait being bound
  impl_type : Ty             -- The implementation type
  deriving Repr

-- Dispatch mode: derived from binding existence
-- Static when binding exists, Dynamic when no binding
inductive DispatchMode where
  | static   -- Monomorphized, direct call (binding exists)
  | dynamic  -- Vtable lookup (no binding, default)
  deriving Repr, BEq, DecidableEq
