library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- soc_top_rv64 — KV260 (Kria K26) board top for the hand-written rv64_exec_core.
--
-- Board variant (Vivado-only): clocked from the Zynq UltraScale+ PS pl_clk0
-- (100 MHz) via the k26_ps_bd block-design wrapper, exactly like the flow in
-- scripts/fpga/build_k26_rv64.shs. Reset is derived from pl_resetn0 plus a
-- short release counter. GHDL cannot elaborate this entity (needs the PS BD +
-- unisim); use soc_top_rv64_sim for simulation. Mirrors soc_top_rv32's board /
-- sim split.
entity soc_top_rv64 is
  generic (
    RESET_RELEASE_COUNT : natural := 255
  );
  port (
    uart_tx : out std_logic;
    uart_rx : in  std_logic
  );
end entity soc_top_rv64;

architecture rtl of soc_top_rv64 is
  signal clk_core  : std_logic;
  signal pl_resetn : std_logic;
  signal rst_q     : std_logic := '1';
  signal rst_cnt   : unsigned(31 downto 0) := (others => '0');
  signal uart_tx_core     : std_logic;
  signal debug_uart_valid : std_logic;
  signal debug_uart_byte  : std_logic_vector(7 downto 0);
  signal marker_idx  : natural range 0 to 17 := 0;
  signal marker_seen : std_logic := '0';
  signal uart_ila_probe : std_logic_vector(9 downto 0);

  -- Zynq PS block-design wrapper (generated by build_k26_rv64.shs). Exposes the
  -- externalised pl_clk0 (100 MHz) + pl_resetn0.
  component k26_ps_bd_wrapper is
    port (
      pl_clk0    : out std_logic;
      pl_resetn0 : out std_logic
    );
  end component;

  -- Marker string "SimpleOS RV64 FPGA" (18 chars) as an ASCII lookup.
  function marker_byte(idx : natural) return std_logic_vector is
    constant MK : string := "SimpleOS RV64 FPGA";
  begin
    return std_logic_vector(to_unsigned(character'pos(MK(idx + 1)), 8));
  end function;

  attribute dont_touch : string;
  attribute mark_debug : string;
  attribute dont_touch of uart_tx_core   : signal is "true";
  attribute mark_debug of uart_tx_core   : signal is "true";
  attribute dont_touch of uart_ila_probe : signal is "true";
  attribute mark_debug of uart_ila_probe : signal is "true";
begin
  uart_tx <= uart_tx_core;
  uart_ila_probe(7 downto 0) <= debug_uart_byte;
  uart_ila_probe(8) <= debug_uart_valid;
  uart_ila_probe(9) <= marker_seen;

  u_ps : k26_ps_bd_wrapper
    port map (
      pl_clk0    => clk_core,
      pl_resetn0 => pl_resetn
    );

  -- Reset release: hold reset until pl_resetn is high AND the release counter
  -- has elapsed.
  process(clk_core)
  begin
    if rising_edge(clk_core) then
      if pl_resetn = '0' then
        rst_cnt <= (others => '0');
        rst_q   <= '1';
      elsif rst_cnt < to_unsigned(RESET_RELEASE_COUNT, rst_cnt'length) then
        rst_cnt <= rst_cnt + 1;
        rst_q   <= '1';
      else
        rst_q <= '0';
      end if;
    end if;
  end process;

  process(clk_core)
  begin
    if rising_edge(clk_core) then
      if rst_q = '1' then
        marker_idx  <= 0;
        marker_seen <= '0';
      elsif debug_uart_valid = '1' then
        if debug_uart_byte = marker_byte(marker_idx) then
          if marker_idx = 17 then
            marker_seen <= '1';
            marker_idx  <= 0;
          else
            marker_idx <= marker_idx + 1;
          end if;
        elsif debug_uart_byte = marker_byte(0) then
          marker_idx <= 1;
        else
          marker_idx <= 0;
        end if;
      end if;
    end if;
  end process;

  u_core : entity work.rv64_exec_core
    generic map (
      CLK_FREQ  => 100_000_000,
      BAUD_RATE => 115_200
    )
    port map (
      clk              => clk_core,
      rst              => rst_q,
      uart_tx          => uart_tx_core,
      debug_uart_valid => debug_uart_valid,
      debug_uart_byte  => debug_uart_byte
    );
end architecture rtl;
