name = "memory_capabilities"
defaultTargets = ["MemoryCapabilities", "MemoryCapabilitiesConstraints"]

[[lean_lib]]
name = "MemoryCapabilities"
srcDir = "src"

[[lean_lib]]
name = "MemoryCapabilitiesConstraints"
srcDir = "src"
roots = ["MemoryCapabilitiesConstraints"]
