-- GENERATED by `simple gen-lean` -- DO NOT EDIT.
-- Regeneration replaces this file wholesale. Hand-written theorems belong in
-- the sibling NogcCompileConstraints.lean, which the generator never writes.

namespace NogcCompile
-- Mini IR with only arithmetic and explicit GC calls.
inductive Instr
  | const : Nat → Instr
  | add
  | gcAlloc

def nogc (p : List Instr) : Prop :=
  ∀ i, i ∈ p → i ≠ Instr.gcAlloc

def append (a : List Instr) (b : List Instr) : List Instr :=
  a ++ b

theorem nogc_append (a : List Instr) (b : List Instr) :
  nogc a → nogc b → nogc (append a b) := by
  intro ha hb i hmem
  have := List.mem_append.mp hmem
  cases this with
  | inl haMem => exact ha _ haMem
  | inr hbMem => exact hb _ hbMem

theorem nogc_singleton (i : Instr) (h : i ≠ Instr.gcAlloc) :
  nogc [i] := by
  intro j hj
  have h' : j = i := by simpa using hj
  subst h'
  exact h

end NogcCompile
