name = "visibility_export"
defaultTargets = ["VisibilityExport", "VisibilityExportConstraints"]

[[lean_lib]]
name = "VisibilityExport"
srcDir = "src"

[[lean_lib]]
name = "VisibilityExportConstraints"
srcDir = "src"
roots = ["VisibilityExportConstraints"]
