#define _GNU_SOURCE
#include <ctype.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <limits.h>
#include <signal.h>
#include <stdint.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/prctl.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

extern char **environ;
static volatile sig_atomic_t interrupted;
static pid_t child_group = -1;

static void on_signal(int sig) { interrupted = sig; if (child_group > 0) kill(-child_group, SIGTERM); }
static void cleanup_group(void) {
 if (child_group <= 0) return;
 kill(-child_group, SIGKILL);
 for (;;) { pid_t p=waitpid(-1,0,WNOHANG); if(p>0)continue; if(p<0&&errno==EINTR)continue; break; }
 child_group=-1;
}
static uint64_t mono_ns(void) { struct timespec t; if (clock_gettime(CLOCK_MONOTONIC, &t)) return 0; return (uint64_t)t.tv_sec*1000000000u+(uint64_t)t.tv_nsec; }
static void die(const char *s) { perror(s); exit(2); }

/* Small, dependency-free SHA-256: the measured executable never depends on a
 * pathname or a helper executable after its descriptor has been opened. */
typedef struct { uint32_t h[8]; uint64_t n; unsigned char b[64]; size_t z; } Sha;
static uint32_t rr(uint32_t x,unsigned n){return(x>>n)|(x<<(32-n));}
static void sx(Sha*s,const unsigned char*p){static const uint32_t k[64]={
0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2};uint32_t w[64],a,b,c,d,e,f,g,h;
for(int i=0;i<16;i++){w[i]=(uint32_t)p[4*i]<<24|(uint32_t)p[4*i+1]<<16|(uint32_t)p[4*i+2]<<8|p[4*i+3];}for(int i=16;i<64;i++){uint32_t x=w[i-15],y=w[i-2];w[i]=(rr(x,7)^rr(x,18)^(x>>3))+w[i-16]+(rr(y,17)^rr(y,19)^(y>>10))+w[i-7];}a=s->h[0];b=s->h[1];c=s->h[2];d=s->h[3];e=s->h[4];f=s->h[5];g=s->h[6];h=s->h[7];for(int i=0;i<64;i++){uint32_t q=h+(rr(e,6)^rr(e,11)^rr(e,25))+((e&f)^(~e&g))+k[i]+w[i],r=(rr(a,2)^rr(a,13)^rr(a,22))+((a&b)^(a&c)^(b&c));h=g;g=f;f=e;e=d+q;d=c;c=b;b=a;a=q+r;}s->h[0]+=a;s->h[1]+=b;s->h[2]+=c;s->h[3]+=d;s->h[4]+=e;s->h[5]+=f;s->h[6]+=g;s->h[7]+=h;}
static void si(Sha*s){uint32_t h[]={0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19};memset(s,0,sizeof(*s));memcpy(s->h,h,sizeof h);}
static void su(Sha*s,const void*v,size_t n){const unsigned char*p=v;s->n+=n;while(n){size_t q=64-s->z;if(q>n)q=n;memcpy(s->b+s->z,p,q);s->z+=q;p+=q;n-=q;if(s->z==64){sx(s,s->b);s->z=0;}}}
static void sf(Sha*s,unsigned char out[32]){uint64_t bits=s->n*8;unsigned char x=0x80;su(s,&x,1);x=0;while(s->z!=56)su(s,&x,1);unsigned char q[8];for(int i=0;i<8;i++)q[7-i]=(unsigned char)(bits>>(8*i));su(s,q,8);for(int i=0;i<8;i++){out[4*i]=s->h[i]>>24;out[4*i+1]=s->h[i]>>16;out[4*i+2]=s->h[i]>>8;out[4*i+3]=s->h[i];}}
static int hash_fd(int fd,char hex[65]){Sha s;si(&s);unsigned char b[32768],d[32];if(lseek(fd,0,SEEK_SET)<0)return-1;for(;;){ssize_t n=read(fd,b,sizeof b);if(n<0){if(errno==EINTR)continue;return-1;}if(!n)break;su(&s,b,(size_t)n);}sf(&s,d);for(int i=0;i<32;i++)sprintf(hex+2*i,"%02x",d[i]);hex[64]=0;return lseek(fd,0,SEEK_SET)<0?-1:0;}

static int absent_file(const char *path) {
 char tmp[PATH_MAX]; if (!path || !*path || strlen(path)>=sizeof tmp) {errno=EINVAL;return-1;} strcpy(tmp,path);
 int d=open(path[0]=='/'?"/":".",O_RDONLY|O_DIRECTORY|O_CLOEXEC); if(d<0)return-1;
 char *p=tmp+(path[0]=='/'); for(;;){while(*p=='/')p++;char *slash=strchr(p,'/');if(!slash)break;*slash=0;if(!*p){close(d);errno=EINVAL;return-1;}int n=openat(d,p,O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC);close(d);if(n<0)return-1;d=n;p=slash+1;}
 if(!*p){close(d);errno=EINVAL;return-1;}int fd=openat(d,p,O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC,0600);close(d);return fd;
}
static int number(const char*s,uint64_t*out){if(!s||!*s||(s[0]=='0'&&s[1])||s[0]=='-'||s[0]=='+')return-1;uint64_t v=0;for(;*s;s++){if(!isdigit((unsigned char)*s))return-1;unsigned d=*s-'0';if(v>(UINT64_MAX-d)/10)return-1;v=v*10+d;}*out=v;return 0;}
static int safe_id(const char*s){size_t n=s?strlen(s):0;if(n<8||n>64)return 0;for(size_t i=0;i<n;i++)if(!isalnum((unsigned char)s[i])&&s[i]!='-'&&s[i]!='_')return 0;return 1;}

typedef struct {pid_t pid,ppid;uint64_t start,rss,hwm,anon,file;} Proc;
static int proc_stat(pid_t pid,Proc*p){char n[64],buf[4096],*r,*q;snprintf(n,sizeof n,"/proc/%ld/stat",(long)pid);int fd=open(n,O_RDONLY|O_CLOEXEC);if(fd<0)return-1;ssize_t z=read(fd,buf,sizeof(buf)-1);close(fd);if(z<=0)return-1;buf[z]=0;r=strrchr(buf,')');if(!r||r[1]!=' ')return-1;q=r+2;int field=3;char*save=0,*t=strtok_r(q," ",&save);p->pid=pid;p->ppid=0;p->start=0;while(t){if(field==4)p->ppid=(pid_t)strtol(t,0,10);if(field==22){if(number(t,&p->start))return-1;break;}field++;t=strtok_r(0," ",&save);}return p->start?0:-1;}
static void proc_mem(Proc*p){char n[64],line[256];snprintf(n,sizeof n,"/proc/%ld/status",(long)p->pid);FILE*f=fopen(n,"r");if(!f)return;while(fgets(line,sizeof line,f)){uint64_t v=0;char key[32];if(sscanf(line,"%31[^:]: %"SCNu64,key,&v)==2){if(!strcmp(key,"VmRSS"))p->rss=v;else if(!strcmp(key,"VmHWM"))p->hwm=v;else if(!strcmp(key,"RssAnon"))p->anon=v;else if(!strcmp(key,"RssFile"))p->file=v;}}fclose(f);}
static int descendant(pid_t pid,pid_t root){pid_t seen=pid;for(int i=0;i<128;i++){Proc p={0};if(proc_stat(seen,&p))return 0;if(seen==root)return 1;if(p.ppid<=1||p.ppid==seen)return 0;seen=p.ppid;}return 0;}
static int sample(int out,const char*id,pid_t root,uint64_t rs){DIR*d=opendir("/proc");if(!d)return-1;struct dirent*e;uint64_t now=mono_ns();int found=0;while((e=readdir(d))){char*x;long v=strtol(e->d_name,&x,10);if(*e->d_name&&!*x&&v>0&&v<=INT_MAX&&descendant((pid_t)v,root)){Proc p={0};if(proc_stat((pid_t)v,&p))continue;proc_mem(&p);if(p.pid==root&&p.start==rs)found=1;dprintf(out,"sample run_id=%s mono_ns=%"PRIu64" root_pid=%ld root_start=%"PRIu64" pid=%ld start=%"PRIu64" ppid=%ld vmrss_kb=%"PRIu64" vmhwm_kb=%"PRIu64" rssanon_kb=%"PRIu64" rssfile_kb=%"PRIu64"\n",id,now,(long)root,rs,(long)p.pid,p.start,(long)p.ppid,p.rss,p.hwm,p.anon,p.file);}}closedir(d);return found?0:-1;}

static uint64_t configured_interval_ms=10000;
static int evidence_usleep(useconds_t requested){if(requested==100000)requested=(useconds_t)(configured_interval_ms*1000);return usleep(requested);}
static int evidence_dprintf(int fd,const char*fmt,...){va_list ap;va_start(ap,fmt);char*s=0;int n=vasprintf(&s,fmt,ap);va_end(ap);if(n<0)return n;if(!strncmp(s,"terminal ",9)&&n&&s[n-1]=='\n'){s[n-1]=0;int r=dprintf(fd,"%s interval_ms=%"PRIu64"\n",s,configured_interval_ms);free(s);return r;}ssize_t w=write(fd,s,(size_t)n);free(s);return w<0?-1:(int)w;}
#define usleep evidence_usleep
#define dprintf evidence_dprintf
enum {K_RUN,K_MONO,K_RPID,K_RSTART,K_PID,K_START,K_PPID,K_RSS,K_HWM,K_ANON,K_FILE,K_EXIT,K_SIGNAL,K_INTERVAL,K_MAX};
static int keyid(const char*s){static const char*k[K_MAX]={"run_id","mono_ns","root_pid","root_start","pid","start","ppid","vmrss_kb","vmhwm_kb","rssanon_kb","rssfile_kb","exit_code","signal","interval_ms"};for(int i=0;i<K_MAX;i++)if(!strcmp(s,k[i]))return i;return-1;}
static int validate(const char*path,const char*want){FILE*f=fopen(path,"r");if(!f){perror(path);return 2;}char line[2048];uint64_t root=0,rs=0,last=0,seen_pid[4096],seen_start[4096];size_t seen_n=0;int samples=0,roots=0,terminal=0,ln=0;while(fgets(line,sizeof line,f)){ln++;size_t z=strlen(line);if(!z||line[z-1]!='\n'){fprintf(stderr,"line %d: partial record\n",ln);goto bad;}line[z-1]=0;char*save=0,*kind=strtok_r(line," ",&save);int term=kind&&!strcmp(kind,"terminal");if(!kind||(!term&&strcmp(kind,"sample"))){fprintf(stderr,"line %d: record type\n",ln);goto bad;}char*vals[K_MAX]={0},*tok;while((tok=strtok_r(0," ",&save))){char*eq=strchr(tok,'=');if(!eq||eq==tok||!eq[1])goto bad;*eq=0;int k=keyid(tok);if(k<0){fprintf(stderr,"line %d: unknown key\n",ln);goto bad;}if(vals[k]){fprintf(stderr,"line %d: duplicate key\n",ln);goto bad;}vals[k]=eq+1;}int req[]={K_RUN,K_MONO,K_RPID,K_RSTART};for(size_t i=0;i<sizeof req/sizeof req[0];i++)if(!vals[req[i]])goto bad;if(strcmp(vals[K_RUN],want)||!safe_id(vals[K_RUN])){fprintf(stderr,"line %d: run id\n",ln);goto bad;}uint64_t n,rp,rst;if(number(vals[K_MONO],&n)||!n||n<last||number(vals[K_RPID],&rp)||!rp||number(vals[K_RSTART],&rst)||!rst)goto bad;last=n;if(!root){root=rp;rs=rst;}else if(root!=rp||rs!=rst){fprintf(stderr,"line %d: root mismatch\n",ln);goto bad;}if(term){if(++terminal>1||!vals[K_EXIT]||!vals[K_SIGNAL]||!vals[K_INTERVAL])goto bad;uint64_t a,b,iv;if(number(vals[K_EXIT],&a)||a>255||number(vals[K_SIGNAL],&b)||b>255||number(vals[K_INTERVAL],&iv)||iv<10||iv>10000)goto bad;for(int k=K_PID;k<=K_FILE;k++)if(vals[k])goto bad;}else{if(terminal||vals[K_INTERVAL])goto bad;for(int k=K_PID;k<=K_FILE;k++)if(!vals[k])goto bad;if(vals[K_EXIT]||vals[K_SIGNAL])goto bad;uint64_t v[K_MAX];for(int k=K_PID;k<=K_FILE;k++)if(number(vals[k],&v[k]))goto bad;if(!v[K_PID]||!v[K_START])goto bad;size_t j;for(j=0;j<seen_n;j++)if(seen_pid[j]==v[K_PID]){if(seen_start[j]!=v[K_START]){fprintf(stderr,"line %d: PID reuse\n",ln);goto bad;}break;}if(j==seen_n){if(seen_n==4096){fprintf(stderr,"identity table full\n");goto bad;}seen_pid[seen_n]=v[K_PID];seen_start[seen_n++]=v[K_START];}samples++;if(v[K_PID]==root){if(v[K_START]!=rs){fprintf(stderr,"line %d: root PID reuse\n",ln);goto bad;}roots++;}}
 }if(ferror(f)||!samples||!roots||terminal!=1){fprintf(stderr,"invalid completeness: samples=%d roots=%d terminal=%d\n",samples,roots,terminal);goto bad;}fclose(f);return 0;bad:fclose(f);return 2;}

static int run(int argc,char**argv){const char*raw=0,*expect=0,*id=0;int sep=-1;for(int i=2;i<argc;i++){if(!strcmp(argv[i],"--raw")&&i+1<argc)raw=argv[++i];else if(!strcmp(argv[i],"--sha256")&&i+1<argc)expect=argv[++i];else if(!strcmp(argv[i],"--run-id")&&i+1<argc)id=argv[++i];else if(!strcmp(argv[i],"--")){sep=i+1;break;}else return 64;}if(!raw||!expect||strlen(expect)!=64||!safe_id(id)||sep<0||sep>=argc)return 64;int exe=open(argv[sep],O_RDONLY|O_CLOEXEC|O_NOFOLLOW);if(exe<0)die("open executable");struct stat before,after;if(fstat(exe,&before)||!S_ISREG(before.st_mode))die("stat executable");char got[65];if(hash_fd(exe,got)||strcmp(got,expect)){fprintf(stderr,"compiler hash mismatch\n");return 2;}if(fstat(exe,&after)||before.st_dev!=after.st_dev||before.st_ino!=after.st_ino){fprintf(stderr,"compiler identity changed\n");return 2;}int out=absent_file(raw);if(out<0)die("raw evidence target");if(prctl(PR_SET_CHILD_SUBREAPER,1,0,0,0))die("subreaper");if(atexit(cleanup_group))die("atexit");int gate[2];if(pipe2(gate,O_CLOEXEC))die("pipe");pid_t pid=fork();if(pid<0)die("fork");if(!pid){close(gate[1]);if(setpgid(0,0))_exit(126);char c;if(read(gate[0],&c,1)!=1)_exit(126);close(gate[0]);fexecve(exe,&argv[sep],environ);_exit(127);}close(gate[0]);child_group=pid;if(setpgid(pid,pid)&&errno!=EACCES)die("setpgid");Proc rootp={0};for(int i=0;i<100&&proc_stat(pid,&rootp);i++)usleep(1000);if(!rootp.start)die("root identity");struct sigaction sa={0};sa.sa_handler=on_signal;sigemptyset(&sa.sa_mask);sigaction(SIGINT,&sa,0);sigaction(SIGTERM,&sa,0);char c='x';if(write(gate[1],&c,1)!=1)die("launch gate");close(gate[1]);int st=0;for(;;){pid_t w=waitpid(pid,&st,WNOHANG);if(w==pid)break;if(w<0&&errno!=EINTR)break;if(interrupted){kill(-pid,SIGKILL);waitpid(pid,&st,0);break;}if(sample(out,id,pid,rootp.start)){kill(-pid,SIGKILL);waitpid(pid,&st,0);dprintf(out,"terminal run_id=%s mono_ns=%"PRIu64" root_pid=%ld root_start=%"PRIu64" exit_code=255 signal=0\n",id,mono_ns(),(long)pid,rootp.start);fsync(out);close(out);return 2;}usleep(100000);}kill(-pid,SIGTERM);int code=WIFEXITED(st)?WEXITSTATUS(st):128+(WIFSIGNALED(st)?WTERMSIG(st):0),sig=WIFSIGNALED(st)?WTERMSIG(st):0;dprintf(out,"terminal run_id=%s mono_ns=%"PRIu64" root_pid=%ld root_start=%"PRIu64" exit_code=%d signal=%d\n",id,mono_ns(),(long)pid,rootp.start,code,sig);if(fsync(out))die("fsync raw");close(out);close(exe);cleanup_group();return interrupted?128+interrupted:code;}

#undef usleep
#undef dprintf
static int run_dispatch(int argc,char**argv){for(int i=2;i<argc;i++)if(!strcmp(argv[i],"--interval-ms")){uint64_t v;if(i+1>=argc||number(argv[i+1],&v)||v<10||v>10000)return 64;configured_interval_ms=v;for(int j=i;j+2<argc;j++)argv[j]=argv[j+2];argc-=2;break;}return run(argc,argv);}
static int known_aux(const char *s) {
 static const char *k[]={"schema","run_id","seq","pid","monotonic_ms","event","phase","source_index","source_path_kind","source_path","retained_modules","validation_keys","validation_values","shared_traits","hir_names","hir_symbols","hir_functions","hir_constants","hir_enums","hir_structs","hir_classes","heap_live_bytes","heap_peak_bytes","rss_kib","hwm_kib"};
 for(size_t i=0;i<sizeof k/sizeof k[0];i++){if(!strcmp(s,k[i]))return(int)i;}return-1;
}
static int aux_stream(const char *path,const char *id,int phase_stream,uint64_t *lo,uint64_t *hi,uint64_t *rows){
 FILE*f=fopen(path,"r");if(!f)return-1;char line[12288];uint64_t want_seq=0;int opens=0,terms=0;*lo=UINT64_MAX;*hi=0;*rows=0;
 while(fgets(line,sizeof line,f)){size_t z=strlen(line);if(!z||line[z-1]!='\n')goto bad;line[z-1]=0;char*vals[25]={0},*save=0,*t=strtok_r(line," ",&save);while(t){char*e=strchr(t,'=');if(!e||e==t||!e[1])goto bad;*e=0;int k=known_aux(t);if(k<0||vals[k])goto bad;vals[k]=e+1;t=strtok_r(0," ",&save);}for(int k=0;k<25;k++)if(!vals[k])goto bad;if(strcmp(vals[0],"simple.compiler.mem_snapshot.v1")||strcmp(vals[1],id))goto bad;uint64_t seq,ms;if(number(vals[2],&seq)||seq!=want_seq++||number(vals[4],&ms)||!ms)goto bad;if(ms<*lo)*lo=ms;if(ms>*hi)*hi=ms;(*rows)++;if(phase_stream){if(strcmp(vals[5],"phase"))goto bad;}else if(!strcmp(vals[5],"open")){if(seq||++opens!=1||terms)goto bad;}else if(!strcmp(vals[5],"terminal")){if(++terms!=1||opens!=1)goto bad;}else if(strcmp(vals[5],"snapshot")||!opens||terms)goto bad;
 }if(ferror(f)||!*rows||(phase_stream?0:(opens!=1||terms!=1)))goto bad;fclose(f);return 0;bad:fclose(f);return-1;
}
static int hash_path(const char*p,char h[65]){int fd=open(p,O_RDONLY|O_NOFOLLOW|O_CLOEXEC);if(fd<0)return-1;struct stat s;if(fstat(fd,&s)||!S_ISREG(s.st_mode)||hash_fd(fd,h)){close(fd);return-1;}close(fd);return 0;}
static int parent_dir(const char*path,char leaf[NAME_MAX+1]){char b[PATH_MAX];if(!path||strlen(path)>=sizeof b){errno=EINVAL;return-1;}strcpy(b,path);char*s=strrchr(b,'/');const char*base;if(s){base=s+1;if(s==b)s[1]=0;else*s=0;}else{strcpy(b,".");base=path;}if(!*base||strlen(base)>NAME_MAX||strchr(base,'/')){errno=EINVAL;return-1;}strcpy(leaf,base);int d=open(b[0]=='/'?"/":".",O_RDONLY|O_DIRECTORY|O_CLOEXEC);if(d<0)return-1;char*p=b+(b[0]=='/');while(*p){while(*p=='/')p++;if(!*p)break;char*q=strchr(p,'/');if(q)*q=0;int n=openat(d,p,O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC);close(d);if(n<0)return-1;d=n;if(!q)break;p=q+1;}return d;}
static int put_file(int d,const char*n,const char*s){int f=openat(d,n,O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC,0600);if(f<0)return-1;size_t z=strlen(s),o=0;while(o<z){ssize_t w=write(f,s+o,z-o);if(w<=0){close(f);return-1;}o+=(size_t)w;}int r=fsync(f);close(f);return r;}
static __attribute__((unused)) uint64_t raw_interval(const char*p){FILE*f=fopen(p,"r");char b[2048];uint64_t v=0;if(!f)return 0;while(fgets(b,sizeof b,f)){char*x=strstr(b," interval_ms=");if(x){x+=13;char*e=strchr(x,'\n');if(e)*e=0;if(number(x,&v))v=0;}}fclose(f);return v;}
static void discard_generation(int pd,const char*tmp){int d=openat(pd,tmp,O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC);if(d>=0){const char*n[]={"receipt.env","summary.env","delta.tsv","boundary.tsv"};for(size_t i=0;i<4;i++)unlinkat(d,n[i],0);close(d);}unlinkat(pd,tmp,AT_REMOVEDIR);}
static uint64_t analyzed_interval_ms;
static int evidence_snprintf(char*out,size_t cap,const char*fmt,...){va_list ap;va_start(ap,fmt);int n=vsnprintf(out,cap,fmt,ap);va_end(ap);if(n<0||(size_t)n>=cap)return n;char*x=strstr(out,"sample_interval_ms=10000\n");if(x){char v[32];int z=snprintf(v,sizeof v,"sample_interval_ms=%"PRIu64"\n",analyzed_interval_ms);size_t old=25,tail=strlen(x+old);if(z<0||(size_t)z+tail+1>cap-(size_t)(x-out))return-1;memmove(x+z,x+old,tail+1);memcpy(x,v,(size_t)z);n+=(int)((size_t)z-old);}return n;}
/* CLOCK_MONOTONIC readings may straddle launch/termination syscalls.  Five
 * milliseconds is the sole endpoint tolerance; it is never applied between
 * records or to sequence validation. */
static int analysis_preflight(const char*samp,const char*mem,const char*phase,const char*id){if(validate(samp,id))return-1;FILE*f=fopen(samp,"r");if(!f)return-1;char b[2048];uint64_t first=0,last=0;while(fgets(b,sizeof b,f)){int sample_line=!strncmp(b,"sample ",7),terminal_line=!strncmp(b,"terminal ",9);if(!sample_line&&!terminal_line)continue;char*x=strstr(b," mono_ns=");if(!x){fclose(f);return-1;}x+=9;char*e=strchr(x,' ');if(!e){fclose(f);return-1;}*e=0;uint64_t ns;if(number(x,&ns)){fclose(f);return-1;}if(sample_line&&!first)first=ns/1000000;if(terminal_line)last=ns/1000000;}fclose(f);analyzed_interval_ms=raw_interval(samp);if(!first||!last||!analyzed_interval_ms)return-1;uint64_t ml,mh,mr,pl,ph,pr;if(aux_stream(mem,id,0,&ml,&mh,&mr)||aux_stream(phase,id,1,&pl,&ph,&pr))return-1;const uint64_t tolerance_ms=5;uint64_t lower=first>tolerance_ms?first-tolerance_ms:0,upper=last>UINT64_MAX-tolerance_ms?UINT64_MAX:last+tolerance_ms;return(ml<lower||mh>upper||pl<lower||ph>upper)?-1:0;}
#define unlinkat(pd,tmp,flags) do { discard_generation((pd),(tmp)); } while(0)
#define snprintf evidence_snprintf
static int analyze(int argc,char**argv){const char*samp=0,*mem=0,*phase=0,*id=0,*out=0,*prov=0;for(int i=2;i<argc;i++){if(!strcmp(argv[i],"--samples")&&i+1<argc)samp=argv[++i];else if(!strcmp(argv[i],"--memory")&&i+1<argc)mem=argv[++i];else if(!strcmp(argv[i],"--phase")&&i+1<argc)phase=argv[++i];else if(!strcmp(argv[i],"--run-id")&&i+1<argc)id=argv[++i];else if(!strcmp(argv[i],"--output-dir")&&i+1<argc)out=argv[++i];else if(!strcmp(argv[i],"--provenance")&&i+1<argc)prov=argv[++i];else return 64;}if(!samp||!mem||!phase||!safe_id(id)||!out)return 64;if(validate(samp,id))return 2;uint64_t ml,mh,mr,pl,ph,pr;if(aux_stream(mem,id,0,&ml,&mh,&mr)||aux_stream(phase,id,1,&pl,&ph,&pr)){fprintf(stderr,"invalid memory/phase stream\n");return 2;}char sh[65],mhsh[65],phsh[65],pvsh[65]="none";if(hash_path(samp,sh)||hash_path(mem,mhsh)||hash_path(phase,phsh)||(prov&&hash_path(prov,pvsh)))return 2;char leaf[NAME_MAX+1],tmp[NAME_MAX+1];int pd=parent_dir(out,leaf);if(pd<0)return 2;struct stat st;if(fstatat(pd,leaf,&st,AT_SYMLINK_NOFOLLOW)==0||errno!=ENOENT){close(pd);return 2;}snprintf(tmp,sizeof tmp,".%s.tmp.%ld",leaf,(long)getpid());if(mkdirat(pd,tmp,0700)){close(pd);return 2;}int gd=openat(pd,tmp,O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC);if(gd<0)goto fail;char b[2048];snprintf(b,sizeof b,"run_id\tsequence\tmonotonic_ms\n%s\t0\t%"PRIu64"\n%s\t%"PRIu64"\t%"PRIu64"\n",id,ml,id,mr-1,mh);if(put_file(gd,"boundary.tsv",b))goto fail;snprintf(b,sizeof b,"run_id\tfrom_ms\tto_ms\tdelta_ms\n%s\t%"PRIu64"\t%"PRIu64"\t%"PRIu64"\n",id,ml,mh,mh-ml);if(put_file(gd,"delta.tsv",b))goto fail;snprintf(b,sizeof b,"run_id=%s\nsample_interval_ms=10000\nmemory_records=%"PRIu64"\nphase_records=%"PRIu64"\nmonotonic_min_ms=%"PRIu64"\nmonotonic_max_ms=%"PRIu64"\n",id,mr,pr,ml<pl?ml:pl,mh>ph?mh:ph);if(put_file(gd,"summary.env",b))goto fail;int bf=openat(gd,"boundary.tsv",O_RDONLY|O_NOFOLLOW|O_CLOEXEC),df=openat(gd,"delta.tsv",O_RDONLY|O_NOFOLLOW|O_CLOEXEC),sf=openat(gd,"summary.env",O_RDONLY|O_NOFOLLOW|O_CLOEXEC);char bh[65],dh[65],suh[65];if(bf<0||df<0||sf<0||hash_fd(bf,bh)||hash_fd(df,dh)||hash_fd(sf,suh)){if(bf>=0)close(bf);if(df>=0)close(df);if(sf>=0)close(sf);goto fail;}close(bf);close(df);close(sf);snprintf(b,sizeof b,"receipt_schema=simple-bootstrap-stage3-rss-evidence-v1\nrun_id=%s\nsamples_sha256=%s\nmemory_sha256=%s\nphase_sha256=%s\nprovenance_sha256=%s\nboundary_sha256=%s\ndelta_sha256=%s\nsummary_sha256=%s\nresult=complete\n",id,sh,mhsh,phsh,pvsh,bh,dh,suh);if(put_file(gd,"receipt.env",b)||fsync(gd)){close(gd);goto fail_pd;}close(gd);if(renameat(pd,tmp,pd,leaf)||fsync(pd))goto fail_pd;close(pd);return 0;fail:if(gd>=0)close(gd);fail_pd:unlinkat(pd,tmp,AT_REMOVEDIR);close(pd);return 2;}
#undef snprintf
static int analyze_checked(int argc,char**argv){const char*s=0,*m=0,*p=0,*id=0;for(int i=2;i<argc;i++){if(!strcmp(argv[i],"--samples")&&i+1<argc)s=argv[++i];else if(!strcmp(argv[i],"--memory")&&i+1<argc)m=argv[++i];else if(!strcmp(argv[i],"--phase")&&i+1<argc)p=argv[++i];else if(!strcmp(argv[i],"--run-id")&&i+1<argc)id=argv[++i];else if((!strcmp(argv[i],"--output-dir")||!strcmp(argv[i],"--provenance"))&&i+1<argc)i++;}if(!s||!m||!p||!id)return 64;if(analysis_preflight(s,m,p,id)){fprintf(stderr,"cross-stream monotonic domain mismatch\n");return 2;}return analyze(argc,argv);}
int main(int argc,char**argv){if(argc>=2&&!strcmp(argv[1],"run"))return run_dispatch(argc,argv);if(argc>=2&&!strcmp(argv[1],"analyze"))return analyze_checked(argc,argv);if(argc==5&&!strcmp(argv[1],"validate")&&!strcmp(argv[2],"--run-id"))return validate(argv[4],argv[3]);fprintf(stderr,"usage: %s run [--interval-ms N] --raw FILE --sha256 HEX --run-id ID -- EXE [ARGS...]\n       %s validate --run-id ID FILE\n       %s analyze --samples RAW --memory SNAPSHOT --phase PROFILE --run-id ID --output-dir ABSENT_DIR [--provenance PATH]\n",argv[0],argv[0],argv[0]);return 64;}
