import { freezeDeep, sha256Hex, canonicalJson } from "../storage/canonical.js";
import { isSnapshotAuthorityPortV1, isViewForSnapshotAuthorityPortV1, isSnapshotAuthorityViewV1, isCanonicalTargetV1, isCanonicalDirectoryTargetV1 } from "../core/snapshot_authority.js";

const PORTS = new WeakSet();
const error = () => freezeDeep({ ok: false, error: { code: "projection_denied" } });
const ok = (value) => freezeDeep({ ok: true, value });
function page(input = {}) {
  if (!input || typeof input !== "object" || Array.isArray(input)) throw new TypeError("page request must be an object");
  const limit = input.limit ?? 100;
  if (!Number.isSafeInteger(limit) || limit < 1 || limit > 100) throw new TypeError("page limit is invalid");
  const cursor = input.cursor ?? "";
  if (typeof cursor !== "string" || cursor.includes("\0")) throw new TypeError("page cursor is invalid");
  return { limit, cursor };
}
function same(view, target) { return target.authority_instance === view.authority_instance && target.snapshot_uid === view.snapshot_uid && target.inventory_root === view.inventory_root && target.manifest_digest === view.manifest_digest; }
function childKey(child) { return Buffer.from(`${child.target_kind}\0${child.target_uid}`, "utf8").toString("base64url"); }

/** The read-only projection boundary. It consumes only proof objects from one authority view. */
export function createProjectionPortV1({ snapshotAuthorityPort } = {}) {
  if (!isSnapshotAuthorityPortV1(snapshotAuthorityPort)) throw new TypeError("ProjectionPortV1 requires a branded SnapshotAuthorityPortV1");
  const port = Object.freeze({
    render(view, target) {
      try {
        if (!isSnapshotAuthorityViewV1(view) || !isViewForSnapshotAuthorityPortV1(snapshotAuthorityPort, view) || !isCanonicalTargetV1(target) || !same(view, target)) return error();
        const bytes = `<!-- generated by SPipe; do not edit -->\n<!-- canonical-${target.target_kind}-uid: ${target.target_uid} -->\n<!-- snapshot-uid: ${view.snapshot_uid} -->\n`;
        return ok(freezeDeep({ type: "projection_document_v1", snapshot_uid: view.snapshot_uid, manifest_digest: view.manifest_digest, target_kind: target.target_kind, target_uid: target.target_uid, bytes, content_digest: `sha256:${sha256Hex(bytes)}` }));
      } catch { return error(); }
    },
    list(view, directoryTarget, pageRequest) {
      try {
        if (!isSnapshotAuthorityViewV1(view) || !isViewForSnapshotAuthorityPortV1(snapshotAuthorityPort, view) || !isCanonicalDirectoryTargetV1(directoryTarget) || !same(view, directoryTarget)) return error();
        const request = page(pageRequest); const children = [...directoryTarget.children].sort((a, b) => childKey(a).localeCompare(childKey(b)));
        const index = request.cursor === "" ? -1 : children.findIndex((child) => childKey(child) === request.cursor);
        if (request.cursor !== "" && index < 0) return error();
        const start = index + 1;
        const entries = children.slice(start, start + request.limit).map((child) => freezeDeep({ ...child, snapshot_uid: view.snapshot_uid, manifest_digest: view.manifest_digest }));
        const next_cursor = start + entries.length < children.length ? childKey(entries.at(-1)) : null;
        const binding = freezeDeep({ snapshot_uid: view.snapshot_uid, manifest_digest: view.manifest_digest, directory_uid: directoryTarget.target_uid, selector_digest: directoryTarget.selector_digest, cursor: request.cursor, next_cursor, entries });
        return ok(freezeDeep({ type: "projection_page_v1", ...binding, page_digest: `sha256:${sha256Hex(canonicalJson(binding))}` }));
      } catch { return error(); }
    }
  }); PORTS.add(port); return port;
}
export function isProjectionPortV1(value) { return PORTS.has(value); }
