name = "module_resolution"
defaultTargets = ["ModuleResolution", "ModuleResolutionConstraints"]

[[lean_lib]]
name = "ModuleResolution"
srcDir = "src"

[[lean_lib]]
name = "ModuleResolutionConstraints"
srcDir = "src"
roots = ["ModuleResolutionConstraints"]
