name = "tensor_dimensions"
defaultTargets = ["TensorDimensions", "TensorMemory", "TensorDimensionsConstraints", "TensorMemoryConstraints"]

[[lean_lib]]
name = "TensorDimensions"
srcDir = "src"
roots = ["TensorDimensions"]

[[lean_lib]]
name = "TensorMemory"
srcDir = "src"
roots = ["TensorMemory"]

[[lean_lib]]
name = "TensorDimensionsConstraints"
srcDir = "src"
roots = ["TensorDimensionsConstraints"]

[[lean_lib]]
name = "TensorMemoryConstraints"
srcDir = "src"
roots = ["TensorMemoryConstraints"]
