name = "macro_auto_import"
defaultTargets = ["MacroAutoImport", "MacroAutoImportConstraints"]

[[lean_lib]]
name = "MacroAutoImport"
srcDir = "src"

[[lean_lib]]
name = "MacroAutoImportConstraints"
srcDir = "src"
roots = ["MacroAutoImportConstraints"]
