import assert from "node:assert/strict";
import test from "node:test";

import { contentHash, deepFreeze } from "../../src/model/identity.js";
import { createArtifactRecord } from "../../src/model/artifact.js";
import { ProjectionKernel, ProjectionUriError, parseCanonicalSpiceUri } from "../../src/view/projection_kernel.js";

const W = "W-01K3R8G3N70ZMT43W6QJ7YHX4P";
const P = "P-01K3R8G3N70ZMT43W6QJ7YHX4P";
const H = contentHash("projection fixture");
const SCOPE = contentHash("project scope");
const SNAPSHOT = "spks1-" + "a".repeat(64);

function artifact(uid, title, path, overrides = {}) {
  return createArtifactRecord({ uid, key: `design.search.${uid.slice(-2).toLowerCase()}`, project_uid: P, revision: "3b676a1", kind: "design", title,
    canonical_path: path, content_hash: H, features: ["search"], components: ["std.common.search"], layers: ["ranking"], status: "approved", ...overrides });
}

function kernel() {
  return new ProjectionKernel({ workspace_uid: W, auth_scope_hash: SCOPE, page_size: 1, inventory: deepFreeze({
    snapshot: { snapshot_uid: SNAPSHOT },
    artifacts: [
      artifact("A-01K3R8G3N70ZMT43W6QJ7YHX4P", "Shared Search", "doc/05_design/search/a.md"),
      artifact("A-01K3R8G3N70ZMT43W6QJ7YHX4Q", "Shared Search", "doc/05_design/search/b.md"),
      artifact("A-01K3R8G3N70ZMT43W6QJ7YHX4R", "Other", "doc/05_design/search/c.md", { features: ["other"] })
    ]
  }) });
}

test("canonical URI parser rejects normalization, traversal, encoding, query, fragment, and devices", () => {
  assert.deepEqual(parseCanonicalSpiceUri(`spipe://workspace/${W}/`), { family: "workspace_root", workspace_uid: W, uri: `spipe://workspace/${W}/` });
  assert.deepEqual(parseCanonicalSpiceUri(`spipe://workspace/${W}/view/feature/search`), { family: "view", workspace_uid: W, view_kind: "feature", segments: ["search"], uri: `spipe://workspace/${W}/view/feature/search` });
  assert.deepEqual(parseCanonicalSpiceUri(`spipe://workspace/${W}/view/feature/`).segments, []);
  for (const uri of [
    `spipe://workspace/${W}`, `spipe://workspace/${W}/view/feature`, `spipe://workspace/${W}/view/feature/%2e%2e`,
    `spipe://workspace/${W}/view/feature/%252f`, `spipe://workspace/${W}/view/feature/..`, `spipe://workspace/${W}/view/feature/a%20b`,
    `spipe://workspace/${W}/view/feature/a?x=1`, `spipe://workspace/${W}/view/feature/a#x`, `spipe://workspace/${W}/view/feature/CON`,
    `spipe://workspace/${W}/view/feature/a\\b`
  ]) assert.throws(() => parseCanonicalSpiceUri(uri), ProjectionUriError, uri);
  assert.throws(() => kernel().list(`spipe://workspace/${W}/view/matrix/a`), /unsupported/);
});

test("projection list is deterministic, collision-safe, bounded, and cursor-bound", () => {
  const view = `spipe://workspace/${W}/view/feature/search`;
  const first = kernel().list(view);
  assert.equal(first.entries.length, 1);
  assert.match(first.entries[0].filename, /^shared-search--A-.*\.md$/);
  assert.equal(first.projection.snapshot_id, SNAPSHOT);
  assert.ok(first.next_cursor);
  const second = kernel().list(view, { cursor: first.next_cursor });
  assert.equal(second.entries.length, 1);
  assert.equal(second.exhausted, true);
  assert.notEqual(first.entries[0].uid, second.entries[0].uid);
  assert.throws(() => kernel().list(`spipe://workspace/${W}/view/feature/other`, { cursor: first.next_cursor }), /binding/);
  assert.throws(() => kernel().list(view, { cursor: first.next_cursor, limit: 2 }), /binding/);
  assert.ok(Object.isFrozen(first));
});

test("projection documents map to one immutable canonical artifact and refuse writes", () => {
  const page = kernel().list(`spipe://workspace/${W}/view/feature/search`);
  const document = kernel().read(`spipe://workspace/${W}/view/feature/search/${page.entries[0].filename}`);
  assert.equal(document.canonical_uid, page.entries[0].uid);
  assert.equal(document.canonical_path, page.entries[0].canonical_path);
  assert.match(document.content, /generated by SPipe/);
  assert.throws(() => kernel().write(), /read-only/);
  assert.throws(() => kernel().list(`spipe://workspace/${W}/view/matrix/a`), /unsupported/);
});

test("kernel rejects a shallow inventory so snapshot identity cannot drift after construction", () => {
  const inventory = Object.freeze({ snapshot: { snapshot_uid: SNAPSHOT }, artifacts: [] });
  assert.throws(() => new ProjectionKernel({ workspace_uid: W, auth_scope_hash: SCOPE, inventory }), /recursively frozen/);
});
