name = "gc_manual_borrow"
defaultTargets = ["GcManualBorrow", "GcManualBorrowConstraints"]

[[lean_lib]]
name = "GcManualBorrow"
srcDir = "src"

[[lean_lib]]
name = "GcManualBorrowConstraints"
srcDir = "src"
roots = ["GcManualBorrowConstraints"]
