#!/bin/bash
# FFI Usage Audit Script
# Finds direct FFI calls (rt_*) without wrappers

set -e

echo "=== FFI Usage Audit ==="
echo ""

# Create temp files
EXTERN_FNS=$(mktemp)
DIRECT_CALLS=$(mktemp)
WRAPPERS=$(mktemp)
REPORT=$(mktemp)

trap "rm -f $EXTERN_FNS $DIRECT_CALLS $WRAPPERS $REPORT" EXIT

# Step 1: Find all extern fn declarations
echo "Step 1: Finding extern fn rt_* declarations..."
find src/ rust/lib/std/src/ -name "*.spl" 2>/dev/null | \
  grep -v "/core/" | \
  xargs grep -n "^extern fn rt_" 2>/dev/null | \
  sed 's/:extern fn /:/g' | \
  sed 's/(.*//g' > "$EXTERN_FNS" || true

echo "Found $(wc -l < "$EXTERN_FNS") extern fn declarations"
echo ""

# Step 2: Find all wrapper functions (fn that calls rt_*)
echo "Step 2: Finding wrapper functions..."
find src/ rust/lib/std/src/ -name "*.spl" 2>/dev/null | \
  grep -v "/core/" | \
  while read file; do
    # For each file, find wrapper patterns
    awk '/^fn [a-z_]+\(/ { fname=$2; gsub(/\(.*/, "", fname) }
         /rt_[a-z_]+\(/ && fname {
           match($0, /rt_[a-z_]+/);
           rt_name = substr($0, RSTART, RLENGTH);
           print fname ":" rt_name;
           fname = "";
         }' "$file" | while IFS=: read wrapper_name rt_name; do
      echo "$file:$wrapper_name:$rt_name"
    done
  done > "$WRAPPERS" || true

echo "Found $(wc -l < "$WRAPPERS") wrapper functions"
echo ""

# Step 3: Find direct rt_* calls (not in extern declarations, not in wrapper definitions)
echo "Step 3: Finding direct FFI calls..."
find src/ test/ rust/lib/std/src/ -name "*.spl" 2>/dev/null | \
  grep -v "/core/" | \
  grep -v "/ffi.spl$" | \
  grep -v "io/mod.spl$" | \
  xargs grep -n "rt_[a-z_]*(" 2>/dev/null | \
  grep -v "^[^:]*:.*extern fn rt_" | \
  grep -v "^[^:]*:.*#.*rt_" > "$DIRECT_CALLS" || true

echo "Found $(wc -l < "$DIRECT_CALLS") potential direct FFI calls"
echo ""

# Step 4: Generate report
echo "Step 4: Generating report..."

cat > "$REPORT" << 'EOF'
# Direct FFI Calls Without Wrappers - Audit Report

## Summary

This report identifies all direct calls to FFI functions (rt_*) that should ideally use wrapper functions following the two-tier pattern.

## FFI Call Analysis

EOF

echo "### Direct FFI Calls by File" >> "$REPORT"
echo "" >> "$REPORT"

# Group by file
current_file=""
cat "$DIRECT_CALLS" | sort | while IFS=: read file line content; do
  if [ "$file" != "$current_file" ]; then
    echo "" >> "$REPORT"
    echo "#### \`$file\`" >> "$REPORT"
    echo "" >> "$REPORT"
    current_file="$file"
  fi

  # Extract rt_function name
  rt_func=$(echo "$content" | grep -o "rt_[a-z_]*(" | head -1 | sed 's/($//')

  echo "- **Line $line**: \`$rt_func()\`" >> "$REPORT"
  echo "  \`\`\`simple" >> "$REPORT"
  echo "  $(echo "$content" | sed 's/^[ \t]*//')" >> "$REPORT"
  echo "  \`\`\`" >> "$REPORT"
done

cat >> "$REPORT" << 'EOF'

## Wrapper Functions Found

The following wrapper functions were detected:

EOF

cat "$WRAPPERS" | awk -F: '{print "- `" $2 "()` → wraps `" $3 "()`"}' | sort -u >> "$REPORT"

cat >> "$REPORT" << 'EOF'

## Recommendations

### Pattern 1: Use Existing Wrapper

If a wrapper exists, import and use it:

```simple
# ❌ Before (direct FFI call)
extern fn rt_file_exists(path: text) -> bool
val exists = rt_file_exists(path)

# ✅ After (use wrapper)
use app.io.{file_exists}
val exists = file_exists(path)
```

### Pattern 2: Create Missing Wrapper

If no wrapper exists, add it to the appropriate FFI module:

**In `src/app/io/mod.spl` or `src/compiler/ffi.spl`:**

```simple
# Tier 1: Extern declaration
extern fn rt_new_function(arg: text) -> i64

# Tier 2: Wrapper function
fn new_function(arg: text) -> i64:
    rt_new_function(arg)

# Export
export new_function
```

### Pattern 3: Add TODO Comment

For temporary direct access (e.g., in tests or prototypes):

```simple
# TODO: Replace with wrapper from app.io once available
extern fn rt_file_exists(path: text) -> bool
val exists = rt_file_exists(path)
```

## Action Items

1. **Review each direct call** - Check if wrapper exists
2. **Update imports** - Use wrappers from `app.io` or `compiler.ffi`
3. **Create missing wrappers** - Add to appropriate FFI module
4. **Add TODO comments** - For cases that can't be fixed immediately
5. **Validate** - Re-run this script after fixes

## Excluded Locations

The following are excluded from this audit (expected to have direct FFI):

- `/core/` - Core runtime implementation
- `/ffi.spl` - FFI declaration modules
- `io/mod.spl` - FFI wrapper module itself
- Wrapper function definitions (where they call the FFI)

## Script Location

This report was generated by: `script/audit_ffi_usage.sh`

To re-run: `bash script/audit_ffi_usage.sh`
EOF

# Save report
mkdir -p doc/report
cp "$REPORT" doc/report/ffi_direct_calls.md

echo "Report saved to: doc/report/ffi_direct_calls.md"
echo ""
echo "Summary:"
echo "  - Extern declarations: $(wc -l < "$EXTERN_FNS")"
echo "  - Wrapper functions: $(wc -l < "$WRAPPERS")"
echo "  - Direct FFI calls: $(wc -l < "$DIRECT_CALLS")"
echo ""
echo "Next steps:"
echo "  1. Review report: cat doc/report/ffi_direct_calls.md"
echo "  2. Fix direct calls by using wrappers or creating them"
echo "  3. Add TODO comments where needed"
