/*
 * Simple Seed — Common CRT Declarations
 *
 * Shared interface between platform-specific startup ASM and C code.
 * Each platform ASM calls __spl_start() which handles the common
 * initialization sequence, then delegates to platform-specific exit.
 */

#ifndef SPL_CRT_COMMON_H
#define SPL_CRT_COMMON_H

#include <stdint.h>

/* Main function prototype (generated by seed compiler) */
extern int main(int argc, char **argv);

/* Runtime initialization (defined in runtime.c) */
extern void spl_init_args(int argc, char **argv);

/* Init/fini arrays (linker-provided) */
typedef void (*init_fn)(void);
extern init_fn __init_array_start[];
extern init_fn __init_array_end[];
extern init_fn __fini_array_start[];
extern init_fn __fini_array_end[];

/*
 * Common startup entry — called by platform ASM after extracting
 * argc/argv from the platform-specific stack layout.
 * Runs constructors, calls main, runs destructors, then exits.
 */
void __spl_start(int argc, char **argv, char **envp);

/*
 * Platform-specific exit — implemented per OS.
 * Never returns.
 */
void __spl_exit(int status) __attribute__((noreturn));

/*
 * Baremetal BSS zeroing — only needed when no OS loader does it.
 * Symbols provided by linker script.
 */
extern char __bss_start[];
extern char __bss_end[];
void __spl_zero_bss(void);

#endif /* SPL_CRT_COMMON_H */
