// runtime_smf_socket_shims.c — host-runtime (SMF loader) TCP socket symbols.
//
// The SMF loader resolves runtime relocations against symbols linked into the
// `simple-runtime` host crate (see RUNTIME_SYMBOL_ENTRIES, generated by
// runtime/build.rs from RUNTIME_SYMBOL_NAMES intersected with DEFINED symbols).
//
// The std.nogc_sync_mut.http_server package transitively references a class of
// rt_io_tcp_* socket externs. Most are Rust-defined in runtime/src/value/net_tcp.rs,
// but these six have NO host-linkable definition — they exist only in
// runtime_native.c, which is compiled into the AOT/native-project lane (an
// independent ABI universe) and is NOT linked into the host runtime. Any SMF that
// links the http_server path therefore fails at load: "Undefined symbol:
// rt_io_tcp_socket_create".
//
// This file provides exactly those six as host-linkable C symbols so the loader's
// static symbol registry can resolve them. build.rs lists this file in BOTH
// `c_sources` (so it links) and `LINKED_C_SOURCES` (so entries are generated).
//
// Note: rt_io_tcp_bind itself is intentionally NOT defined here — it is owned by
// the Rust runtime (net_tcp.rs) and would collide. Five of the six are
// self-contained POSIX wrappers taking only integer fd/flag arguments.
//
// rt_io_tcp_bind_fd takes a `text` address argument whose decoding requires the
// host RuntimeValue text ABI (not the C RtCoreString ABI used by runtime_native.c).
// It is provided here as a link-resolving stub returning failure (-1/0), mirroring
// the freestanding convention in runtime_native.c. The benchmark workload never
// invokes it; a functional host impl belongs in net_tcp.rs (Rust) and is out of
// scope for this change.

#include <stdint.h>

#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  include <winsock2.h>
#  include <ws2tcpip.h>
#  pragma comment(lib, "Ws2_32.lib")

static void _ws_init(void) {
    static int done = 0;
    if (!done) { WSADATA wd; WSAStartup(MAKEWORD(2,2), &wd); done = 1; }
}

int64_t rt_io_tcp_socket_create(int64_t family) {
    _ws_init();
    int af = (family == 6) ? AF_INET6 : AF_INET;
    SOCKET s = socket(af, SOCK_STREAM, IPPROTO_TCP);
    return (s == INVALID_SOCKET) ? -1 : (int64_t)s;
}

int64_t rt_io_tcp_listen(int64_t fd, int64_t backlog) {
    return listen((SOCKET)fd, (int)backlog) == 0 ? 1 : 0;
}

int64_t rt_io_tcp_set_nonblocking(int64_t fd, int64_t enabled) {
    u_long mode = enabled ? 1 : 0;
    return ioctlsocket((SOCKET)fd, FIONBIO, &mode) == 0 ? 1 : 0;
}

int64_t rt_io_tcp_set_reuseaddr(int64_t fd, int64_t enabled) {
    int flag = enabled ? 1 : 0;
    return setsockopt((SOCKET)fd, SOL_SOCKET, SO_REUSEADDR, (const char*)&flag, sizeof(flag)) == 0 ? 1 : 0;
}

int64_t rt_io_tcp_set_reuseport(int64_t fd, int64_t enabled) {
    /* SO_REUSEPORT is not available on Windows; return 0 (not supported). */
    (void)fd; (void)enabled; return 0;
}

#else /* POSIX */

#include <fcntl.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>

int64_t rt_io_tcp_socket_create(int64_t family) {
    int af = (family == 6) ? AF_INET6 : AF_INET;
    return (int64_t)socket(af, SOCK_STREAM, 0);
}

int64_t rt_io_tcp_listen(int64_t fd, int64_t backlog) {
    return listen((int)fd, (int)backlog) == 0 ? 1 : 0;
}

int64_t rt_io_tcp_set_nonblocking(int64_t fd, int64_t enabled) {
    int flags = fcntl((int)fd, F_GETFL, 0);
    if (flags < 0) return 0;
    if (enabled) flags |= O_NONBLOCK; else flags &= ~O_NONBLOCK;
    return fcntl((int)fd, F_SETFL, flags) == 0 ? 1 : 0;
}

int64_t rt_io_tcp_set_reuseaddr(int64_t fd, int64_t enabled) {
    int flag = enabled ? 1 : 0;
    return setsockopt((int)fd, SOL_SOCKET, SO_REUSEADDR, &flag, sizeof(flag)) == 0 ? 1 : 0;
}

int64_t rt_io_tcp_set_reuseport(int64_t fd, int64_t enabled) {
#ifdef SO_REUSEPORT
    int flag = enabled ? 1 : 0;
    return setsockopt((int)fd, SOL_SOCKET, SO_REUSEPORT, &flag, sizeof(flag)) == 0 ? 1 : 0;
#else
    (void)fd; (void)enabled; return 0;
#endif
}

#endif /* _WIN32 */

// Link-resolving stub: see header note. Requires host RuntimeValue text ABI to be
// functional; provided here only so relocations resolve for the never-invoked path.
int64_t rt_io_tcp_bind_fd(int64_t fd, int64_t addr_val) {
    (void)fd; (void)addr_val;
    return 0;
}
