//! Simple Standard Library Tests
//!
//! This module includes auto-generated test functions for Simple standard
//! library tests. The tests are generated by build.rs and included via
//! the OUT_DIR mechanism.
//!
//! # Running Tests
//!
//! Run all Simple stdlib tests:
//! ```bash
//! cargo test -p simple-driver simple_stdlib
//! ```
//!
//! Run tests for a specific module:
//! ```bash
//! cargo test -p simple-driver simple_stdlib_unit_doctest
//! ```
//!
//! # Test Discovery
//!
//! Tests are discovered from `simple/std_lib/test/` directory:
//! - `*_spec.spl` - BDD-style specification tests
//! - `*_test.spl` - Traditional test files
//! - Files in `fixtures/` directories are skipped

// Include the generated test functions
include!(concat!(env!("OUT_DIR"), "/simple_stdlib_tests.rs"));
