//! Simple Standard Library Tests
//!
//! This module includes auto-generated test functions for Simple standard
//! library tests from `simple/std_lib/test/`. The tests are generated by
//! build.rs and included via the OUT_DIR mechanism.
//!
//! For system-level CLI tests, see `simple_tests.rs` which covers tests
//! from `simple/test/`.
//!
//! # Running Tests
//!
//! Run all Simple stdlib tests:
//! ```bash
//! cargo test -p simple-driver --test simple_stdlib_tests
//! ```
//!
//! Run tests for a specific module:
//! ```bash
//! cargo test -p simple-driver simple_stdlib_unit_core
//! cargo test -p simple-driver simple_stdlib_system_doctest
//! cargo test -p simple-driver simple_stdlib_unit_ui
//! ```
//!
//! # Test Discovery
//!
//! Tests are discovered from `simple/std_lib/test/` directory:
//! - `*_spec.spl` - BDD-style specification tests
//! - `*_test.spl` - Traditional test files
//! - Files in `fixtures/` directories are skipped
//!
//! # Test Organization
//!
//! - `unit/` - Unit tests for stdlib modules (core, ui, units, spec, etc.)
//! - `system/` - Framework system tests (doctest, spec)
//! - `integration/` - Cross-module integration tests

// Include the generated test functions
include!(concat!(env!("OUT_DIR"), "/simple_stdlib_tests.rs"));
