FROM ubuntu@sha256:4fbb8e6a8395de5a7550b33509421a2bafbc0aab6c06ba2cef9ebffbc7092d90

ARG DEBIAN_FRONTEND=noninteractive
ARG QEMU_VERSION=1:8.2.2+ds-0ubuntu1.18
ARG MESA_VERSION=25.2.8-0ubuntu0.24.04.2

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      qemu-system-x86="$QEMU_VERSION" \
      qemu-system-common="$QEMU_VERSION" \
      qemu-system-gui="$QEMU_VERSION" \
      qemu-system-modules-opengl="$QEMU_VERSION" \
      libegl1=1.7.0-1build1 \
      libegl-mesa0="$MESA_VERSION" \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/qemu-system-x86_64"]
