name = "nogc_compile"
defaultTargets = ["NogcCompile", "NogcCompileConstraints"]

[[lean_lib]]
name = "NogcCompile"
srcDir = "src"

[[lean_lib]]
name = "NogcCompileConstraints"
srcDir = "src"
roots = ["NogcCompileConstraints"]
