import MemoryCapabilities

def main : IO Unit := do
  IO.println "Memory Capability System Verification"
  IO.println "======================================"
  IO.println ""
  IO.println "This module provides formal verification of the reference"
  IO.println "capability system (Shared, Exclusive, Isolated)."
  IO.println ""
  IO.println "Key theorems:"
  IO.println "  - exclusive_is_unique: Exclusive refs are unique"
  IO.println "  - isolated_is_unique: Isolated refs are unique"
  IO.println "  - exclusive_prevents_aliasing: Exclusive prevents all aliasing"
  IO.println "  - isolated_prevents_aliasing: Isolated prevents all aliasing"
  IO.println "  - conversion_is_safe: Capability conversions preserve safety"
  IO.println "  - wellformed_no_conflicts: Well-formed envs have no conflicts"
  IO.println "  - capabilities_prevent_races: Type system prevents data races"
  IO.println "  - actor_mode_safety: Actor mode enforces no shared mutable state"
  IO.println ""
  IO.println "Verified capabilities:"
  IO.println "  - T (Shared): Multiple read-only references"
  IO.println "  - mut T (Exclusive): Single mutable reference"
  IO.println "  - iso T (Isolated): Unique reference, no aliases"
  IO.println ""
  IO.println "See src/MemoryCapabilities.lean for full formalization."
