name = "async_compile"
defaultTargets = ["AsyncCompile", "AsyncCompileConstraints"]

[[lean_lib]]
name = "AsyncCompile"
srcDir = "src"

[[lean_lib]]
name = "AsyncCompileConstraints"
srcDir = "src"
roots = ["AsyncCompileConstraints"]
