# Generated by Simple Language - sum(1..10) test
# Expected LED value: 55

.section .text
.globl _start
_start:
    li   a0, 0             # sum = 0
    li   a1, 1             # i = 1
    li   a2, 11            # limit = 11
loop:
    add  a0, a0, a1        # sum += i
    addi a1, a1, 1         # i++
    blt  a1, a2, loop      # if i < 11, loop
    lui  t0, 0x80000       # LED base = 0x80000000
    sw   a0, 0(t0)         # LED = sum
    ecall                   # halt
