//! Simple Language System Tests
//!
//! This module includes auto-generated test functions for Simple system tests
//! from `simple/test/` directory. The tests are generated by build.rs and
//! included via the OUT_DIR mechanism.
//!
//! # Running Tests
//!
//! Run all Simple system tests:
//! ```bash
//! cargo test -p simple-driver --test simple_tests
//! ```
//!
//! Run tests for a specific subsystem:
//! ```bash
//! cargo test -p simple-driver simple_test_system_compiler
//! cargo test -p simple-driver simple_test_system_interpreter
//! cargo test -p simple-driver simple_test_system_watcher
//! cargo test -p simple-driver simple_test_system_features
//! ```
//!
//! # Test Discovery
//!
//! Tests are discovered from `simple/test/` directory:
//! - `*_spec.spl` - BDD-style specification tests
//! - `*_test.spl` - Traditional test files
//! - Files in `fixtures/` directories are skipped
//!
//! # Test Organization
//!
//! - `system/compiler/` - Compiler CLI system tests
//! - `system/interpreter/` - Interpreter CLI system tests
//! - `system/watcher/` - File watcher system tests
//! - `system/features/` - Language feature system tests (65+ tests)

// Include the generated test functions
include!(concat!(env!("OUT_DIR"), "/simple_tests.rs"));
